export const iconImports = {
  phone: () => import("@fortawesome/free-solid-svg-icons/faPhone"),
  envelope: () => import("@fortawesome/free-solid-svg-icons/faEnvelope"),
  user: () => import("@fortawesome/free-solid-svg-icons/faUser"),
  home: () => import("@fortawesome/free-solid-svg-icons/faHome"),
  facebook: () => import("@fortawesome/free-brands-svg-icons/faFacebook"),
  twitter: () => import("@fortawesome/free-brands-svg-icons/faTwitter"),
  pe: () => import("@fortawesome/free-solid-svg-icons/faDumbbell"),
  academic: () => import("@fortawesome/free-solid-svg-icons/faBook"),
  dashboard: () => import("@fortawesome/free-solid-svg-icons/faTachographDigital"),
  schools: () => import("@fortawesome/free-solid-svg-icons/faSchool"),
  students: () => import("@fortawesome/free-solid-svg-icons/faUserGraduate"),
  sessions: () => import("@fortawesome/free-solid-svg-icons/faChalkboardTeacher"),
  meals: () => import("@fortawesome/free-solid-svg-icons/faUtensils"),
  workers: () => import("@fortawesome/free-solid-svg-icons/faUsers"),
  trainings: () => import("@fortawesome/free-solid-svg-icons/faBriefcase"),
};
