"""mmade school_id nullable for user to enable multi school management

Revision ID: 12b3f2d6cdd0
Revises: 9c14d1b7f671
Create Date: 2025-07-20 18:40:16.111847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b3f2d6cdd0'
down_revision = '9c14d1b7f671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
