"""Added an expire for a guest

Revision ID: 662954e038f0
Revises: bb577390b438
Create Date: 2025-07-23 18:17:21.446041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662954e038f0'
down_revision = 'bb577390b438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('id_number')

    # ### end Alembic commands ###
