"""added a maintance model

Revision ID: 9c14d1b7f671
Revises: cb16a6eb8770
Create Date: 2025-07-18 15:07:01.157749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c14d1b7f671'
down_revision = 'cb16a6eb8770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specs', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('student_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.Enum('term1', 'term2', 'term3', name='termenum'), nullable=False))
        batch_op.create_index(batch_op.f('ix_student_sessions_term'), ['term'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('student_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_sessions_term'))
        batch_op.drop_column('term')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('specs')

    # ### end Alembic commands ###
