"""added contact number and email field to school and seed

Revision ID: cb16a6eb8770
Revises: 6c247b132848
Create Date: 2025-07-16 14:52:52.513551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb16a6eb8770'
down_revision = '6c247b132848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
